### ISSUE TITLE
NFStreamer(source=file).to_pandas() return empty dataframe

### ISSUE THREAD

**Issue by foongminwong** [nfstream/nfstream#104]
**Describe the bug**
I am trying to read a pcap file exported from Wireshark  downloaded from [here](https://www.unb.ca/cic/datasets/vpn.html), however it returns an empty dataframe after running `to_pandas()`.

**To Reproduce**
Here's the codes running in Jupyter Notebook:

```
from nfstream import NFStreamer, NFPlugin
file="vpn_bittorrent.pcap"
my_dataframe = NFStreamer(source=file).to_pandas()
my_dataframe
```

**Expected behavior**
The pcap is 360MB and not empty, so we should expect the columns to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/23441795/155118221-ba2e13f1-cf6b-49d3-9341-f360c5dc6d80.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version 3.10
 - NFStream version 6.4.2

**Additional context**
N/A

**Comment by foongminwong** [comment]
Here's a link to the particular pcap file: [vpn_bittorrent.pcap](https://www.dropbox.com/s/ahtxqamdan9x40p/vpn_bittorrent.pcap?dl=0)

**Comment by foongminwong** [comment]
Thank you for your reply!

- I run the exact same code in Jupyter Notebook, and somehow it prints `None`

![image](https://user-images.githubusercontent.com/23441795/156332336-ba1d2f9b-2e81-40ab-8894-959ae47c7f98.png)

- I also tried the same way as how you ran the `test.py` and here's the error:

![test](https://user-images.githubusercontent.com/23441795/156334185-cb811525-dc5e-42d8-8761-1bd16d3d4e65.png)

Detailed error messages:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\User\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\User\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\User\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\User\anaconda3\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\User\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\User\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Documents\Research\test.py", line 3, in <module>
    my_dataframe = NFStreamer(source=file).to_pandas()
  File "C:\Users\User\anaconda3\lib\site-packages\nfstream\streamer.py", line 491, in to_pandas
    total_flows = self.to_csv(path=temp_file_path, columns_to_anonymize=columns_to_anonymize, flows_per_file=0)
  File "C:\Users\User\anaconda3\lib\site-packages\nfstream\streamer.py", line 463, in to_csv
    for flow in self:
  File "C:\Users\User\anaconda3\lib\site-packages\nfstream\streamer.py", line 379, in __iter__
    meters[i].start()
  File "C:\Users\User\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\User\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\User\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\User\anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\User\anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
None
```

I'm trying to figure out why it throws errors, probably it might be due to Windows OS... Well, I'm going to switch to macOS or try running it in different machines then 😂

**Comment by foongminwong** [comment]
Yes, this seems like a Windows problem.. After running the code on a Linux virtual machine, it works with no errors. Thank you for your help!

**Comment by aouinizied** [comment]
This is fixed by https://github.com/nfstream/nfstream/commit/00449108bd3b2726f5507bb37e036691fd6d7253 and this patch will be part on next the release.

**Comment by foongminwong** [comment]
Thank you @aouinizied ! Just tested and it's working now in Windows
