### ISSUE TITLE
ValueError: CPU number 44 is not eligible; choose between [0, 1]

### ISSUE THREAD

**Issue by smith558** [nfstream/nfstream#149]
**Desktop (please complete the following information):**
```
lscpu
```
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               2099.871
CPU max MHz:           2100.0000
CPU min MHz:           1000.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              22528K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
NUMA node2 CPU(s):     32-47
NUMA node3 CPU(s):     48-63
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d
```

**Additional context**
Running in `Jupyter Lab 3.5.1`
**Describe the bug**
using `bigFlows.pcap` from https://tcpreplay.appneta.com/wiki/captures.html in
```
from nfstream import NFStreamer

offline_streamer = NFStreamer(source="/lyceum/sm4u19/sm4u19/bigFlows.pcap",
                              statistical_analysis=True,
                              splt_analysis=10)

df = offline_streamer.to_pandas()
```
I get these errors:
```
Process ForkProcess-86:
Process ForkProcess-87:
Process ForkProcess-88:
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
Traceback (most recent call last):
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
Process ForkProcess-89:
Process ForkProcess-90:
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Process ForkProcess-91:
OSError: [Errno 22] Invalid argument
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Process ForkProcess-92:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process ForkProcess-93:
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Process ForkProcess-94:
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
OSError: [Errno 22] Invalid argument
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
OSError: [Errno 22] Invalid argument
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
OSError: [Errno 22] Invalid argument
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
ValueError: CPU number 10 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
ValueError: CPU number 16 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)

During handling of the above exception, another exception occurred:

OSError: [Errno 22] Invalid argument
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
ValueError: CPU number 12 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
ValueError: CPU number 14 is not eligible; choose between [0, 1]
ValueError: CPU number 18 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
ValueError: CPU number 22 is not eligible; choose between [0, 1]
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
Process ForkProcess-100:
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process ForkProcess-101:
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
ValueError: CPU number 26 is not eligible; choose between [0, 1]
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
Process ForkProcess-103:
Process ForkProcess-102:
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
ValueError: CPU number 20 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
Traceback (most recent call last):
Process ForkProcess-104:
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

OSError: [Errno 22] Invalid argument
Process ForkProcess-105:

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
Traceback (most recent call last):
Process ForkProcess-106:
Process ForkProcess-107:
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
Traceback (most recent call last):
Process ForkProcess-108:
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
OSError: [Errno 22] Invalid argument
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
OSError: [Errno 22] Invalid argument
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))

During handling of the above exception, another exception occurred:

ValueError: CPU number 24 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

During handling of the above exception, another exception occurred:

  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
ValueError: CPU number 40 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
ValueError: CPU number 38 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
ValueError: CPU number 44 is not eligible; choose between [0, 1]
ValueError: CPU number 50 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
ValueError: CPU number 42 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
ValueError: CPU number 52 is not eligible; choose between [0, 1]
ValueError: CPU number 46 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
ValueError: CPU number 48 is not eligible; choose between [0, 1]
  File "/lyceum/sm4u19/.conda/envs/ml/lib/python3.9/site-packages/psutil/_pslinux.py", line 2124, in cpu_affinity_set
    raise ValueError(
ValueError: CPU number 54 is not eligible; choose between [0, 1]
```

Any guidance, please?

**Comment by smith558** [comment]
I should add some context. I am running within the SLURM job scheduler (https://slurm.schedmd.com/) on university HPC clusters which have dynamic jobs CPU allocation through affinity.

**Comment by smith558** [comment]
Any guidance for this? @aouinizied  Am I at least able to suppress these warnings somehow maybe?

**Comment by aouinizied** [comment]
@smith558 if you build from source, the  issue should be fixed (https://github.com/nfstream/nfstream/pull/158) and will be integrated in the next release.

**Comment by smith558** [comment]
> @smith558 if you build from source, the issue should be fixed (#158) and will be integrated in the next release.

That's great to hear. 🙂 Appreciate your work on the library!
