### ISSUE TITLE
Setting CPU affinity fails in dockerized Gitlab CI

### ISSUE THREAD

**Issue by Schwaggot** [nfstream/nfstream#157]
**Describe the bug**
When unit testing code that involves running NFStreamer a dockerized CI setup on Gitlab fails for setting the CPU affinity with an `OSError: [Errno 22] Invalid argument` when calling `psutil.Process().cpu_affinity(list(temp[idx % x]))` in line 156 of `utils.py`. 

Assumption is that setting CPU affinity does not work well with dockerized CI setups like Gitlab or Kubernetes. My proposition is to simply wrap it in a try/except block since setting the affinity is rather a nice-to-have feature and not necessarily relevant for the actual functioning. I will create a Pull request for that.

**To Reproduce**
Not reproducible as part of normal running on a desktop. It appears when running unit tests in Gitlab CI where NFStream runs within a docker container.

**Expected behavior**
No error thrown.

**Error Log**
```
Process ForkProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/builds/REDACTED/venv/lib/python3.9/site-packages/nfstream/meter.py", line 198, in meter_workflow
    set_affinity(root_idx+1)
  File "/builds/REDACTED/venv/lib/python3.9/site-packages/nfstream/utils.py", line 156, in set_affinity
    psutil.Process().cpu_affinity(list(temp[idx % x]))
  File "/builds/REDACTED/venv/lib/python3.9/site-packages/psutil/__init__.py", line 825, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/builds/REDACTED/venv/lib/python3.9/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
  File "/builds/REDACTED/venv/lib/python3.9/site-packages/psutil/_pslinux.py", line 2113, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument
```

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Python version 3.9
 - NFStream version 6.5.3

**Comment by smith558** [comment]
Seems related to #149
