### ISSUE TITLE
ImportError: DLL load failed while importing _lib_engine

### ISSUE THREAD

**Issue by ImmEve** [nfstream/nfstream#161]
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nfstream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\software\Python\lib\site-packages\nfstream\__init__.py", line 17, in <module>
    from .streamer import NFStreamer
  File "D:\software\Python\lib\site-packages\nfstream\streamer.py", line 25, in <module>
    from .meter import meter_workflow
  File "D:\software\Python\lib\site-packages\nfstream\meter.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "D:\software\Python\lib\site-packages\nfstream\engine\__init__.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "D:\software\Python\lib\site-packages\nfstream\engine\engine.py", line 16, in <module>
    from _lib_engine import ffi, lib
ImportError: DLL load failed while importing _lib_engine: 找不到指定的模块。

**Comment by aouinizied** [comment]
@ImmEve Is it possible to have more context about this issues as we are unable to reproduce it on WIndows platform.

**Comment by YozoOba** [comment]
I got the same error while running the examples in my windows 10 with python 3.8.
```
from nfstream import NFStreamer

# We display all streamer parameters with their default values.
# See documentation for detailed information about each parameter.
# https://www.nfstream.org/docs/api#nfstreamer
my_streamer = NFStreamer(source="1.pcap",  # or live network interface
                         decode_tunnels=True,
                         bpf_filter=None,
                         promiscuous_mode=True,
                         snapshot_length=1536,
                         idle_timeout=120,
                         active_timeout=1800,
                         accounting_mode=0,
                         udps=None,
                         n_dissections=20,
                         statistical_analysis=False,
                         splt_analysis=0,
                         n_meters=0,
                         max_nflows=0,
                         performance_report=0,
                         system_visibility_mode=0,
                         system_visibility_poll_ms=100)

for flow in my_streamer:
    print(flow)
```
The error is below:
```
Traceback (most recent call last):

    from _lib_engine import ffi, lib
ImportError: DLL load failed while importing _lib_engine: The specified module could not be found
```
I guess the reason may be that windows is missing some dll files,but I don't know which dll fiiles is missing and how to fix.

**Comment by CloudStrifer** [comment]
I also encountered the same problem. Have you resolved it

**Comment by tce** [comment]
Same problem on MacBookPro, M1Max, 13.3.1

❯ **python3**
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> **from nfstream import NFStreamer**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/nfstream/__init__.py", line 17, in <module>
    from .streamer import NFStreamer
  File "/opt/homebrew/lib/python3.11/site-packages/nfstream/streamer.py", line 25, in <module>
    from .meter import meter_workflow
  File "/opt/homebrew/lib/python3.11/site-packages/nfstream/meter.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "/opt/homebrew/lib/python3.11/site-packages/nfstream/engine/__init__.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "/opt/homebrew/lib/python3.11/site-packages/nfstream/engine/engine.py", line 16, in <module>
    from _lib_engine import ffi, lib
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/_lib_engine.abi3.so, 0x0002): symbol not found in flat namespace '_ndpi_category_get_name'
>>>

**Comment by SCU-Yecheng** [comment]
same question, need help

**Comment by SCU-Yecheng** [comment]
> same question, need help

I figure this question out by running the nfstream on a ubuntu rather than windows, still not know how to get over it on windows.

**Comment by Guygolpur** [comment]
same problem
windows machine
python 3.11.4

**Comment by CMV-1** [comment]
D:\anaconda3\envs\nfstream\python.exe

ImportError: DLL load failed while importing _lib_engine: 

Process finished with exit code 1

**Comment by ImmEve** [comment]
I have solved the problem. WinPcap needs to be installed

**Comment by salarshad** [comment]
> I have solved the problem. WinPcap needs to be installed

Did you install npcap? WinPcap has ceased development.

**Comment by CloudStrifer** [comment]
> I have solved the problem. WinPcap needs to be installed

I also think that should be the reason

**Comment by xyyr-c** [comment]
> > I have solved the problem. WinPcap needs to be installed
> 
> Did you install npcap? WinPcap has ceased development.

I install the npcap and solve the problem
