### ISSUE TITLE
Issue with windows10 installation

### ISSUE THREAD

**Issue by dareth-koh** [nfstream/nfstream#184]
**Describe the bug**
Error installation with command - python3 -m pip install -r dev_requirements.txt

**To Reproduce**
run the command in mingw64.exe 
python3 -m pip install -r dev_requirements.txt

**Expected behavior**

**Screenshots**
![image](https://github.com/nfstream/nfstream/assets/17133035/1761d03a-7dbf-444c-b380-48834d91094b)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Python version Python 3.10.12
 - NFStream version current_version = 6.5.4

**Additional context**

**Comment by CMV-1** [comment]
ERROR:Window11
D:\anaconda3\envs\nfstream\python.exe E:\pcap_process\process_pcap_to_csv.py 
Traceback (most recent call last):
  File "E:\pcap_process\process_pcap_to_csv.py", line 1, in <module>
    from nfstream import NFStreamer
  File "D:\anaconda3\envs\nfstream\lib\site-packages\nfstream\__init__.py", line 17, in <module>
    from .streamer import NFStreamer
  File "D:\anaconda3\envs\nfstream\lib\site-packages\nfstream\streamer.py", line 25, in <module>
    from .meter import meter_workflow
  File "D:\anaconda3\envs\nfstream\lib\site-packages\nfstream\meter.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "D:\anaconda3\envs\nfstream\lib\site-packages\nfstream\engine\__init__.py", line 16, in <module>
    from .engine import create_engine, setup_capture, setup_dissector, activate_capture
  File "D:\anaconda3\envs\nfstream\lib\site-packages\nfstream\engine\engine.py", line 16, in <module>
    from _lib_engine import ffi, lib
ImportError: DLL load failed while importing _lib_engine: 找不到指定的模块。

Process finished with exit code 1
