### ISSUE TITLE
Can not install nfstream on Freebsd

### ISSUE THREAD

**Issue by fateme81** [nfstream/nfstream#186]
I tried to install nfstream from source and here is the errors : 

`      /tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/cparser.py:154: UserWarning: String literal found in cdef() or type source. String literals are ignored here, but you should remove them anyway because some character sequences confuse pre-parsing.
        warnings.warn("String literal found in cdef() or type source. "
      Traceback (most recent call last):
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/cparser.py", line 336, in _parse
          ast = _get_parser().parse(fullcsource)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/pycparser/c_parser.py", line 147, in parse
          return self.cparser.parse(
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 331, in parse
          return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
          tok = call_errorfunc(self.errorfunc, errtoken, self)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
          r = errorfunc(token)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/pycparser/c_parser.py", line 1931, in p_error
          self._parse_error(
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/pycparser/plyparser.py", line 67, in _parse_error
          raise ParseError("%s: %s" % (coord, msg))
      pycparser.plyparser.ParseError: <cdef source string>:573:25: before: __attribute__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 680, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-sh3d24y4/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 700, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "nfstream/engine/engine_build.py", line 206, in <module>
          ffi_builder.cdef(NDPI_CDEF, override=True)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/api.py", line 112, in cdef
          self._cdef(csource, override=override, packed=packed, pack=pack)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/api.py", line 126, in _cdef
          self._parser.parse(csource, override=override, **options)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/cparser.py", line 389, in parse
          self._internal_parse(csource)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/cparser.py", line 394, in _internal_parse
          ast, macros, csource = self._parse(csource)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/cparser.py", line 338, in _parse
          self.convert_pycparser_error(e, csource)
        File "/tmp/pip-build-env-sh3d24y4/normal/lib/python3.9/site-packages/cffi/cparser.py", line 367, in convert_pycparser_error
          raise CDefError(msg)
      cffi.CDefError: cannot parse "long long __max_align1 __attribute__((__aligned__(_Alignof(long long))));"
      <cdef source string>:573:25: before: __attribute__
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

my pip list  : 
`cffi       1.16.0
click      8.1.7
cparser    0.3.1
numpy      1.25.0
parglare   0.16.0
pip        23.3
pycparser  2.21
pyelftools 0.29
SciPy      1.11.1
setuptools 58.2.0`

can you please help me on this.

**Comment by YoshuaCarlson** [comment]
I think you shoud start by:- 

1.) Installing required dependencies such as autoconf, automake, libtool, pkg-config, and gettext using pkg install or ports (FreeBSD’s package manager).
json-c using pkg install or ports.

2.) Clone the nfstream repository using git or download the source tarball.
Change into the cloned directory and run python setup.py install to build and install nfstream using pip.

Note: You may need to configure your Python environment and pip to use the correct architecture (e.g., 64-bit) and version (e.g., Python 3.x).

If you’re using a FreeBSD version older than 13, you might need to install Python 3.x manually, as it’s not included in the base system.
If you’re using a FreeBSD version 13 or newer, Python 3.x is included, and you can proceed with installing nfstream using pip.

You can also refer to this resource:- https://www.nfstream.org/docs/#installation-guide

Hope this helps!
