### ISSUE TITLE
NFPlugin and active_timeout

### ISSUE THREAD

**Issue by zambery** [nfstream/nfstream#59]
Hello!

I'm doing a plugin to get the payload from a pcap. And I set the `active_timeout=3600` when I read the pcap, because of this I got 8 flows from it.

But the pcap actually has 5 flows, and I don't know how to use the parameter `active_timeout=3600` in the plugin, so I can get 8 flows' payload. 

Because the number of flows obtained in the plugin does not match the number of flows obtained by NFStream, `to_pandas()` cannot be used.

```
Traceback (most recent call last):
  File "/home/amber/PycharmProjects/MultiModel/test.py", line 49, in <module>
    stream_df = stream.to_pandas()
  File "/home/amber/anaconda3/envs/DL/lib/python3.8/site-packages/nfstream/streamer.py", line 362, in to_pandas
    df = pd.read_csv(temp_file_path)
  File "/home/amber/anaconda3/envs/DL/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/amber/anaconda3/envs/DL/lib/python3.8/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/home/amber/anaconda3/envs/DL/lib/python3.8/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/amber/anaconda3/envs/DL/lib/python3.8/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 80 fields in line 6, saw 99
```

Thanks for your help!

**Comment by aouinizied** [comment]
@zambery I'm not sure I'm understanding your issue. Active timeout is a parameter of your Streamer. 
Whatever you start a streamer with plugins or not, you will have the same flow count.
Can you share your plugin source code and your pcap in order to address your issue. From the traces I see, it's more related to csv to pandas conversion more than active timeout. 

Zied

**Comment by zambery** [comment]
> @zambery I'm not sure I'm understanding your issue. Active timeout is a parameter of your Streamer.
> Whatever you start a streamer with plugins or not, you will have the same flow count.
> Can you share your plugin source code and your pcap in order to address your issue. From the traces I see, it's more related to csv to pandas conversion more than active timeout.
> 
> Zied

I find I was wrong. As you say, it's the problem of csv to pandas. Thanks for your help.
