### ISSUE TITLE
Running on Raspberry Pi 4: Error with "dissector"

### ISSUE THREAD

**Issue by Arri** [nfstream/nfstream#70]
**Describe the bug**
I installed NFStream on a Raspberry Pi 4 following the instructions "Building NFStream from sources" on https://www.nfstream.org/docs/ (no pip install ). All works fine (just for nDPI I had to install some more libraries, which are mentioned following the given link), besides:
My issue is that I only get results if I set **n_dissections=0**. If **n_dissections** is set to another value than 0, I get following error message:

> sudo python3 flow1.py 

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/flowmeter/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/home/pi/flowmeter/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/flowmeter/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/home/pi/flowmeter/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/flowmeter/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/home/pi/flowmeter/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
```

**To Reproduce**

I am trying following simple code (but get same result with e.g. the given nfstream/test.py):
```
from nfstream import NFStreamer
my_streamer = NFStreamer( source="wlan0",
                                              n_dissections=2,
                                              statistical_analysis=False,
                                              splt_analysis=10)
for flow in my_streamer:
    print(flow) 
```

**Expected behavior**
With **n_dissections=0** the output is e.g.:
```
NFlow(id=1,
      expiration_id=0,
      src_ip=---.---.--.---,
      src_mac=--:--:--:--:--:--,
      src_oui=--:--:--,
      src_port=37528,
      dst_ip=--.-.54.254,
      dst_mac=--:--:--:--:--:--,
      dst_oui=--:--:--,
      dst_port=443,
      protocol=6,
      ip_version=4,
      vlan_id=0,
      tunnel_id=0,
      bidirectional_first_seen_ms=1628824361218,
      bidirectional_last_seen_ms=1628824361451,
      bidirectional_duration_ms=233,
      bidirectional_packets=20,
      bidirectional_bytes=7833,
      src2dst_first_seen_ms=1628824361218,
      src2dst_last_seen_ms=1628824361413,
      src2dst_duration_ms=195,
      src2dst_packets=12,
      src2dst_bytes=3126,
      dst2src_first_seen_ms=1628824361258,
      dst2src_last_seen_ms=1628824361451,
      dst2src_duration_ms=193,
      dst2src_packets=8,
      dst2src_bytes=4707,
      splt_direction=[0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
      splt_ps=[74, 66, 54, 571, 1514, 54, 1026, 66, 1514, 54],
      splt_piat_ms=[0, 40, 0, 1, 43, 0, 3, 0, 0, 0])
```
(note: I replaced mac and ip values manually with '-')

**Desktop (please complete the following information):**
 - OS: "Raspbian GNU/Linux 10 (buster)"
 - Python version: 3.7.3
 - NFStream version: 6.3.4

**Additional context**
I run the python code with
> sudo python3 test.py

**Comment by aouinizied** [comment]
@Arri  this is fixed in https://github.com/nfstream/nfstream/commit/a15e3fb44e586dc092ef7ed6a4637faec2bf9013. Can you confirm?

**Comment by Arri** [comment]
Hi @Zied,
Thank you. Don't see the issue anymore.
I repeated only the last step to build NFStream from here
<https://www.nfstream.org/docs/>.
I noted that the revision number (6.3.4) has not changed.

Thanks
