### ISSUE TITLE
mp.set_start_method("fork") causing RuntimeError: context has already been set

### ISSUE THREAD

**Issue by rasheed-rd** [nfstream/nfstream#74]
**Describe the bug**
I have a project I want to use NFStreamer in that uses multiprocessing. I'm setting the start method to fork using `mp.set_start_method("fork")`. When trying to import and use NFStreamer this causes a runtime error b/c streamer.py on [line 32](https://github.com/nfstream/nfstream/blob/master/nfstream/streamer.py#L32) is also setting the start method to fork, according to the python docs it should only be used once.
> set_start_method() should not be used more than once in the program

**To Reproduce**
```
import multiprocessing as mp
from nfstream import NFStreamer

def main():
    mp.set_start_method("fork")

if __name__ == "__main__":
     main()
```

**Expected behavior**
According to the python docs the `set_start_method()` should be used in the `if __name__ == '__main__' ` clause.

> To select a start method you use the set_start_method() in the if __name__ == '__main__' clause of the main module

Alternatively, using [get_context("fork")](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_context) could solve the problem. 

I'm interested in hearing your thoughts.

**Desktop (please complete the following information):**
 - OS: [MacOS 11.6, Debian GNU/Linux 11]
 - Python version [3.9.6]
 - NFStream version [6.3.4]

**Comment by aouinizied** [comment]
@rasheed-rd Nice catch! Thanks for reporting.
Indeed `mp.set_start_method("fork")` was used to avoid issue on OSX. It needs to be changed to `mp_context = get_context("fork")` where `mp_context` is a private attribute of Streamer object.
I can patch it unless you want to provide us with a PR (this would be a great first contribution). What do you think?

Zied

**Comment by rasheed-rd** [comment]
@aouinizied Thanks for the prompt response. It would be a great first contribution. I'll go ahead and create a PR for it, hopefully get it in by tomorrow. 

Rasheed

**Comment by rasheed-rd** [comment]
@aouinizied I made the changes [here](https://github.com/rasheed-rd/nfstream/commit/387e032ccbf619c454d3c31db6a6c09ba3bb9f67) but did not create a PR b/c I can't get the tests to run. I followed the instructions in the CONTRIBUTING document but I'm getting the following error, any guidance?
I'm running it on MacOS 11.6, tried python 3.6.15 and python 3.9.6. 

```
└[~/projects/nfstream]> python tests.py 

----------------------------------------------------------------------
.Test accounting_mode parameter                                 : OK
.
----------------------------------------------------------------------
.Test active_timeout parameter                                  : OK
.
----------------------------------------------------------------------
Process ForkProcess-2:
Process ForkProcess-3:
Process ForkProcess-4:
Process ForkProcess-1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
ValueError: Error while initializing dissector.
Traceback (most recent call last):
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
ValueError: Error while initializing dissector.
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process ForkProcess-5:
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
Process ForkProcess-6:
Traceback (most recent call last):
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
Traceback (most recent call last):
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
Process ForkProcess-7:
Traceback (most recent call last):
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rasheed/.pyenv/versions/3.6.15/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 208, in meter_workflow
    dissector = setup_dissector(ffi, lib, n_dissections)
  File "/Users/rasheed/projects/nfstream/nfstream/meter.py", line 139, in setup_dissector
    raise ValueError("Error while initializing dissector.")
ValueError: Error while initializing dissector.
```

**Comment by aouinizied** [comment]
@rasheed-rd well done!
Tests are not passing due to 2 reasons:
* You should resync your branch in order to have a fix I pushed yesterday.
* Check the updated instructions in CONTRIBUTING, libgcrypt and libgpg-error versions are updated. So need to rebuild dependencies with these new versions and rerun setup bdist_wheel.

Thanks for your contribution.

Zied

**Comment by rasheed-rd** [comment]
@aouinizied Thanks! That took care of those errors. When I ran the tests locally they all passed except for `test_source_parameter` which hangs on source `lo0`. It hangs with and w/o the changes. Is there something I'm missing that'll help make this test pass on macOS 11.6?

**Comment by aouinizied** [comment]
@rasheed-rd Thanks!  CI tests are passing on macos. Maybe the issue is that you runned tests.py as root which make lo0 accessible and thus script are waiting for a flow expiration instead of raising an expected exception. Did you run tests as root ?

**Comment by rasheed-rd** [comment]
No, I ran them as my local user. It does appear the lo0 was accessible though.

**Comment by aouinizied** [comment]
@rasheed-rd Ok will change it then. You confirm that it is correctly working when you run live capture (idle_timeout to 1) to avoid waiting 120 secs.
